---
- name: Role example
  hosts: debian2
  roles:
    - development

  tasks:
    - name: Last tasks
      debug:
        msg: "Hello, World"

    - name: Include roles
      ansible.builtin.include_role:
        name: development

  post_tasks:
    - name: Info
      debug:
        msg: "Finished"
