---
- name: Test play
  hosts: app_servers

  tasks:
    - name: ping
      ansible.builtin.ping:
    - name: Create a file
      ansible.builtin.shell: 
        touch /tmp/file.txt

- name: Install nginx
  hosts: debian

  tasks:
    - name: stop Apache
      include_tasks: add_task.yaml

    - name: Install nginx
      ansible.builtin.apt:
         name: nginx
         state: latest
         update_cache: true 

    - name: Up nginx
      ansible.builtin.service:
        name: nginx
        state: started

    - name: Copy a file
      ansible.builtin.copy:
        src: ./resources/index.html
        dest: /var/www/html
        owner: root
        group: root
        mode: '0664'
      
    

...
        
