#SPDX-License-Identifier: MIT-0
---
# tasks file for development
- name: Install {{software}}
  apt:
    name: "{{software}}"
    state: present
  when: ansible_facts['distribution'] | lower == 'debian'

- name: start {{service}}
  service:
    name: "{{service}}"
    state: started
  when: ansible_facts['distribution'] | lower == 'debian'
  notify:
    - copy_sql_script
    - create_db
