all:
  hosts:
  children:
    ubuntu:
      hosts:
        ubuntu1:
    debian:
      hosts:
        debian1:
          v2: "hello, debian1"
        debian2:
    rocky:
      hosts:
        rocky1:
        rocky2:
    data_servers:
      hosts:
        mysql1:
    app_servers:
      hosts:
        tomcat1:
        tomcat2:
