- name: Test with variables
  hosts: debian1
  vars:
    message: "Hello, World"
    course: "Ansible"
    env:
      type: linux 
      mem: 4GB
      disc: 500GB
     
  tasks:
   - name: see vars
     debug:
      msg: "Current state: {{env}} {{env.type}} {{env.mem}} {{env.disc}}"
   